### ISSUE TITLE
Question about GuiAndConsole

### ISSUE THREAD

**Issue by luebbe** [JensBorrisholt/DelphiConsole#15]
Whenever an application is compiled as a gui app, there is no problem to attach this application to to the parent console and send output to it.
But - and this effect is also visible in the GuiAndConsole demo - the parent console seems to have no idea that there was some text output and that the current cursor position and prompt should be e.g. 5 or 500 lines further down.

If you run GuiAndConsole and press **Enter** when done, the dos prompt shows up in the middle of the text that was output in the console window by the demo.
Do you have any idea how to tell the parent console where the prompt and cursor should be? Is this possible?

**Comment by JensBorrisholt** [comment]
Hi luebbe

First of all thankyou for contributing to the project. 

You are not forgotten, Ill look over your stuff within the next days,

**Comment by luebbe** [comment]
Hi Jens,

thanks for your reply. No Problem. I know we're all doing a lot of stuff in our free time 👍 

I was trying to spice up the GuiAndConsole application to become a real "four-way" application. It could be started from a dos prompt or "windows run" or explorer and it should be able to switch to gui or console mode no matter from where it was started, when the user tells it to switch to a certain mode.

The code below doesn't work yet in all cases (Win32/64, Debugger yes/no). I think `AllocateConsole` needs some refactoring and `IsAttached` could be made smarter too. 

**GuiAndConsole.dpr**

```pascal
procedure RunInConsole(FromGUI: boolean);
begin
  Console.WriteLine('Print text in current Console Window.');

  if Console.IsAttached then
    Console.WriteLine('Attaching twice to the same console returns true')
  else
    Console.WriteLine('I''m sad');

  // If started from GUI prompt user to press a key
  if FromGUI then
    begin
      Console.Write('Press enter to exit');
      Console.ReadLine;
    end;
end;

procedure RunInGUI;
begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end;

begin
  // Autodetect if the app was started from console or windows
  if Console.IsAttached then
    begin
      // Forced into GUI mode via command line
      if FindCmdLineSwitch('gui') then
        RunInGui
      else
        RunInConsole(false);
    end
  else
    begin
      // Forced into console mode via command line
      if FindCmdLineSwitch('console') then
        begin
          Console.AutoAllocateConsole := true;
          Console.AllocateConsole;
          RunInConsole(true);
        end
      else
        RunInGui;
    end;
end.
```

My current experiments with IsAttached, but I haven't yet come to a good conclusion how to combine `Success` with the results from `GetLastError`. `AllocateConsole` also doesn't take this into account yet. Also not sure whether IsAttached should really call AllocateConsole, so bits are missing right now.

```pascal
class function Console.IsAttached: Boolean;
var
  Success:boolean;
begin
//  {$IFNDEF Win32}
//    if IsDebuggerPresent then
//      Exit(false);
//  (*
//    In the case of a 64-bit debug, it appears that the IDE is creating a console for the debugger,
//    which hosts the debugged application as a child, and so electing to attach to the parent console succeeds.
//
//    This console is not created for a 32-bit debug session.
//  *)
//  {$ENDIF}

  Success := AttachConsole(ATTACH_PARENT_PROCESS);

//  if Result then
  case GetLastError of
    5: // Access denied: already attached to console, we can return true
      Result := true;
    6: // Invalid handle: we don't have a console
      Result := false;
    else // 187 under Win64 Debugger
      Result := false;
  end;
end;


```

**Comment by JensBorrisholt** [comment]
Very interesting. I've merged your changed into the Development branch I suggest we continue on there and you can make merge request onto that one. And when it's working it will be branched into master. 

I've redefined ATTACH_PARENT_PROCESS because it wasn't defined in older Delphi versions.  I'm unsure when it made its way into the RTL but it isn't there in Delphi XE7. 

This lib can compile in alle unicode versions of Delphi

**Comment by luebbe** [comment]
> 
> If you run GuiAndConsole and press **Enter** when done, the dos prompt shows up in the middle of the text that was output in the console window by the demo.
> Do you have any idea how to tell the parent console where the prompt and cursor should be? Is this possible?

In the mean time I have found out, that the windows prompt appears correctly when a "hybrid" application is run in cmd. If the same application is run in powershell, the windows prompt appears in the middle of the application's output.
