### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by limelect** [JensBorrisholt/DelphiConsole#2]
Delphi 10.2
demo under debug !!!!
system error 87
parameter is incorrect

procedure TPixel.SetPos(AxPos, AyPos: Integer);
var
  OldVisible: Boolean;
begin
  OldVisible := Visible;

  try
    Visible := False; <<<<<<< error

and took it off then game start and again
same error

**Comment by JensBorrisholt** [comment]
AxPos, AyPos might not be valid the first time this function is called. Thats why it is encapsulated in a Try Except block.

Goto Options --> Embarcadero Debuggers -> Language Exceptions, and uncheck the "Notify on language exceptions" check box.
